=== jhuska/arquillian-unified-recorder/arquillian-recorder-reporter/src/main/resources/xsd/report.xsd
<xs:schema xmlns="http://jboss.org/schema/arquillian/recorder/reporter" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://jboss.org/schema/arquillian/recorder/reporter" version="1.0">
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="suite" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="suite">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="class" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="className" />
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="test" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="test">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testName" />
                <xs:element ref="result" />
                <xs:element minOccurs="0" ref="duration" />
                <xs:element minOccurs="0" ref="screenshots" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="result" type="xs:NCName" />
    <xs:element name="duration">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="unit" use="optional" default="second">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="second|minute|hour" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="screenshots">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="screenshot" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="screenshot">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="when" />
                <xs:element ref="file" />
                <xs:element ref="type" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="when" type="xs:NCName" />
    <xs:element name="file" type="xs:string" />
    <xs:element name="type" type="xs:NCName" />
    <xs:element name="className" type="xs:NCName" />
    <xs:element name="testName" type="xs:NCName" />
</xs:schema>

=== jhuska/arquillian-unified-recorder/arquillian-recorder-reporter/test.xml
<report xmlns="http://jboss.org/schema/arquillian/recorder/reporter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jboss.org/schema/arquillian/recorder/reporter https://raw2.github.com/smiklosovic/arquillian-unified-recorder/reporter/arquillian-recorder-reporter/src/main/resources/xsd/report.xsd">
    <suite>
        <class>
            <className>org.aerogear.push.testcase</className>
            <test>
                <testName>someFakeTest</testName>
                <result>passed</result>
                <duration unit="second">45</duration>
                <screenshots>
                    <screenshot>
                        <when>before</when>
                        <file>screenshots/someTest/screen.png</file>
                        <type>png</type>
                    </screenshot>
                </screenshots>
            </test>
            <test>
                <testName>someOtherFakeTest</testName>
                <result>passed</result>
                <duration unit="minute">20</duration>
                <screenshots>
                    <screenshot>
                        <when>before</when>
                        <file>screenshots/someTest/screen.png</file>
                        <type>png</type>
                    </screenshot>
                    <screenshot>
                        <when>after</when>
                        <file>screenshots/someTest/screen.png</file>
                        <type>png</type>
                    </screenshot>
                </screenshots>
            </test>
        </class>
        <class>
            <className>org.aerogear.push.other.testcase</className>
            <test>
                <testName>someFakeTest2</testName>
                <result>passed</result>
                <duration unit="hour">12</duration>
                <screenshots>
                    <screenshot>
                        <when>before</when>
                        <file>screenshots/someTest/screen.png</file>
                        <type>png</type>
                    </screenshot>
                    <screenshot>
                        <when>before</when>
                        <file>screenshots/someTest/screen2.png</file>
                        <type>png</type>
                    </screenshot>
                </screenshots>
            </test>
            <test>
                <testName>someOtherFakeTest3</testName>
                <result>passed</result>
                <duration>8</duration>
            </test>
        </class>
    </suite>
</report>
